# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoJianBiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CeHuiShouFei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaDiDingZhuang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BaDiDingZhuangShuliang', models.FloatField()),
                ('BaDiDingZhuangShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YanXian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YanXianShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YanXianShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JunGongCeLiang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JunGongCeLiangShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JunGongCeLiangShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuanJiaZiXun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuanJiaZiXunShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuanJiaZiXunShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiTuCeHui', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiTuCeHuiShuliang', models.FloatField()),
                ('DiTuCeHuiShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JiaoFeiDanWei', models.CharField(max_length=50)),
                ('ShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DangAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FaGaiPiWen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FaGaiPiWen', models.CharField(max_length=50)),
                ('FaWenRiQi', models.DateField()),
                ('YongDiMianJi', models.FloatField()),
                ('JianSheGuiMo', models.CharField(max_length=50)),
                ('JianZhuMianJi', models.FloatField()),
                ('TouZi', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FangChanCeHui',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
                ('diShangmiji', models.FloatField()),
                ('JiRongMianJi', models.FloatField()),
                ('ZhuZeMianJi', models.FloatField()),
                ('GongJianMianJi', models.FloatField()),
                ('ShangYeMianJi', models.FloatField()),
                ('FeiJiRongMianJi', models.FloatField()),
                ('DiXiaMianJi', models.FloatField()),
                ('JiaKongCenMianJi', models.FloatField()),
                ('RongJiLu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GuiHuaFangAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('PiZhunRiQi', models.DateField()),
                ('YongDiMianJi', models.FloatField()),
                ('JianZhuMianJi', models.FloatField()),
                ('JiRongMianJi', models.FloatField()),
                ('ZhuZeMianJi', models.FloatField()),
                ('GongJianMianJi', models.FloatField()),
                ('ShangYeMianJi', models.FloatField()),
                ('FeiJiRongMianJi', models.FloatField()),
                ('DiXiaMianJi', models.FloatField()),
                ('JiaKongCenMianJi', models.FloatField()),
                ('RongJiLu', models.FloatField()),
                ('ZhanDiMianJi', models.FloatField()),
                ('JianZhuMiDu', models.FloatField()),
                ('LuDiMianJi', models.FloatField()),
                ('LuDiLu', models.FloatField()),
                ('TingCheWei', models.FloatField()),
                ('BeiZhu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuoTuZhengJian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WenJian', models.CharField(max_length=50)),
                ('FaWengRiQi', models.DateField()),
                ('BianHao', models.CharField(max_length=50)),
                ('BanZhengRiQi', models.DateField()),
                ('YongDiMianJi', models.FloatField()),
                ('YongDixinzhi', models.CharField(max_length=50)),
                ('ZongDiTuBianHao', models.CharField(max_length=50)),
                ('HeTong', models.CharField(max_length=50)),
                ('BeiZhu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HuanJingYingXiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HuanWei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JianSheDanWei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JianSheDanWei', models.CharField(max_length=128)),
                ('DiZhi', models.CharField(max_length=128)),
                ('FaDingDaiBiaoRen', models.CharField(max_length=8)),
                ('FaDingDaiBiaoRenDianHua', models.CharField(max_length=11)),
                ('LianXiRen', models.CharField(max_length=8)),
                ('LianXiRenDianHua', models.CharField(max_length=11)),
                ('DanWeiDianHua', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='JianSheGongChengGuiHuaXuKe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaoJianRiQi', models.DateField()),
                ('ZiBianHao', models.CharField(max_length=50)),
                ('ShangBaoRiQi', models.DateField()),
                ('YiJian', models.TextField()),
                ('BianHao', models.CharField(max_length=50)),
                ('JianSheGuiMo', models.TextField()),
                ('JianZhuMianJi', models.FloatField()),
                ('BeiZhu', models.TextField()),
                ('BanZhengRiQi', models.DateField()),
                ('LinZhengRiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JiChuSheShiFei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZhuZe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuZeShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuZeShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeiZhuZe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeiZhuZeShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeiZhuZeShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LinShiXiangMu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LinShiXiangMuShuliang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LinShiXiangMuShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ShouFei', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JunGongCeLiang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
                ('YongDiMianJi', models.FloatField()),
                ('ZhanDiMianJi', models.FloatField()),
                ('JianZhuMiDu', models.FloatField()),
                ('LuDiMianJi', models.FloatField()),
                ('LuDiLu', models.FloatField()),
                ('TingCheWei', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='JunGongGuiHuaYanShou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaoJianRiQi', models.DateField()),
                ('ZiBianHao', models.CharField(max_length=50)),
                ('ShangBaoRiQi', models.DateField()),
                ('GenZongFuWuBiao', models.CharField(max_length=50)),
                ('BeiZhu', models.TextField()),
                ('YiJian', models.TextField()),
                ('BianHao', models.CharField(max_length=50)),
                ('BanZhengRiQi', models.DateField()),
                ('LinZhengRiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KaiGongTongJiDengJiBiao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='KangZheng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LuHuaJingGuanFangAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('ShengDingRiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='QiangGai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RenFang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('RiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShiGongTu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('TuShengDanWei', models.CharField(max_length=50)),
                ('TuShengRiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShouFeiBiaoZhun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BaDiDingZhuang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('YanXian', models.DecimalField(decimal_places=2, max_digits=10)),
                ('JunGongCeLiang', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuanJiaZiXun', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DiTuCeHui', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ZhuZe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FeiZhuZe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('LinShiXiangMu', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='XiangMu',
            fields=[
                ('BianHao', models.AutoField(primary_key=True, serialize=False)),
                ('MinCheng', models.CharField(max_length=128)),
                ('JianShedidian', models.CharField(max_length=128)),
                ('FaGaiPiWen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guihua.FaGaiPiWen')),
                ('JianSheDanWei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guihua.JianSheDanWei')),
            ],
        ),
        migrations.CreateModel(
            name='XuanZhiYiJianShu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('BanZhengRiQi', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='YongDiGuiHuaTiaoJian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BianHao', models.CharField(max_length=50)),
                ('PiZhunRiQi', models.DateField()),
                ('WeiZhi', models.CharField(max_length=50)),
                ('YongDiMianJi', models.FloatField()),
                ('YongDixinzhi', models.CharField(max_length=50)),
                ('RongJiLu', models.FloatField()),
                ('JianZhuMiDu', models.FloatField()),
                ('LuDiLu', models.FloatField()),
                ('BeiZhu', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='YongDiGuiHuaXuKe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ZiBianHao', models.CharField(max_length=50)),
                ('BaoJianRiQi', models.DateField()),
                ('ShangBaoRiQi', models.DateField()),
                ('BeiZhu', models.TextField()),
                ('ShengChaYiJian', models.TextField()),
                ('BianHao', models.CharField(max_length=50)),
                ('BanZhengRiQi', models.DateField()),
                ('YongDixinzhi', models.CharField(max_length=50)),
                ('YongDiMianJi', models.FloatField()),
                ('JianZhuMianJi', models.FloatField()),
                ('LinZhengRiQi', models.DateField()),
            ],
        ),
    ]
