# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guihua', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaoJianBiao',
        ),
        migrations.DeleteModel(
            name='CeHuiShouFei',
        ),
        migrations.DeleteModel(
            name='DangAn',
        ),
        migrations.DeleteModel(
            name='FangChanCeHui',
        ),
        migrations.DeleteModel(
            name='GuiHuaFangAn',
        ),
        migrations.DeleteModel(
            name='GuoTuZhengJian',
        ),
        migrations.DeleteModel(
            name='HuanJingYingXiang',
        ),
        migrations.DeleteModel(
            name='HuanWei',
        ),
        migrations.DeleteModel(
            name='JianSheGongChengGuiHuaXuKe',
        ),
        migrations.DeleteModel(
            name='JiChuSheShiFei',
        ),
        migrations.DeleteModel(
            name='JunGongCeLiang',
        ),
        migrations.DeleteModel(
            name='JunGongGuiHuaYanShou',
        ),
        migrations.DeleteModel(
            name='KaiGongTongJiDengJiBiao',
        ),
        migrations.DeleteModel(
            name='KangZheng',
        ),
        migrations.DeleteModel(
            name='LuHuaJingGuanFangAn',
        ),
        migrations.DeleteModel(
            name='QiangGai',
        ),
        migrations.DeleteModel(
            name='RenFang',
        ),
        migrations.DeleteModel(
            name='ShiGongTu',
        ),
        migrations.DeleteModel(
            name='ShouFeiBiaoZhun',
        ),
        migrations.RemoveField(
            model_name='xiangmu',
            name='FaGaiPiWen',
        ),
        migrations.RemoveField(
            model_name='xiangmu',
            name='JianSheDanWei',
        ),
        migrations.DeleteModel(
            name='XuanZhiYiJianShu',
        ),
        migrations.DeleteModel(
            name='YongDiGuiHuaTiaoJian',
        ),
        migrations.DeleteModel(
            name='YongDiGuiHuaXuKe',
        ),
        migrations.DeleteModel(
            name='FaGaiPiWen',
        ),
        migrations.DeleteModel(
            name='JianSheDanWei',
        ),
        migrations.DeleteModel(
            name='XiangMu',
        ),
    ]
