# Generated by Django 2.0.3 on 2018-05-14 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JianSheDanWei',
            fields=[
                ('BianHao', models.AutoField(primary_key=True, serialize=False)),
                ('JianSheDanWei_Name', models.CharField(max_length=128)),
                ('JianSheDanWei_DiZhi', models.CharField(max_length=128)),
                ('JianSheDanWei_FaDingDaiBiaoRen', models.CharField(max_length=8)),
                ('JianSheDanWei_FaDingDaiBiaoRenDianHua', models.CharField(max_length=11)),
                ('JianSheDanWei_LianXiRen', models.CharField(max_length=8)),
                ('JianSheDanWei_LianXiRenDianHua', models.CharField(max_length=11)),
                ('JianSheDanWei_DianHua', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='XiangMu',
            fields=[
                ('BianHao', models.AutoField(primary_key=True, serialize=False)),
                ('MinCheng', models.CharField(max_length=128)),
                ('JianShedidian', models.CharField(max_length=128)),
                ('creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('JianSheDanWei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.JianSheDanWei')),
            ],
        ),
    ]
