# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
    ]
