# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20180515_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaGaiPiWen',
            fields=[
                ('BianHao', models.AutoField(primary_key=True, serialize=False)),
                ('PiWen', models.CharField(max_length=50)),
                ('FaWenRiQi', models.DateField()),
                ('YongDiMianJi', models.FloatField()),
                ('JianSheGuiMo', models.CharField(max_length=50)),
                ('JianZhuMianJi', models.FloatField()),
                ('TouZi', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_DiZhi',
            new_name='DiZhi',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_DianHua',
            new_name='DianHua',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_FaDingDaiBiaoRen',
            new_name='FaDingDaiBiaoRen',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_FaDingDaiBiaoRenDianHua',
            new_name='FaDingDaiBiaoRenDianHua',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_LianXiRen',
            new_name='LianXiRen',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_LianXiRenDianHua',
            new_name='LianXiRenDianHua',
        ),
        migrations.RenameField(
            model_name='jianshedanwei',
            old_name='JianSheDanWei_Name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='xiangmu',
            name='FaGaiPiWen',
            field=models.ManyToManyField(to='plan.FaGaiPiWen'),
        ),
    ]
