# Generated by Django 2.0.3 on 2018-05-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20180515_1941'),
    ]

    operations = [
    ]
