# Generated by Django 2.0.3 on 2018-05-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20180515_2113'),
    ]

    operations = [
    ]
