# Generated by Django 2.0.3 on 2018-05-22 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20180522_1736'),
    ]

    operations = [
    ]
