# Generated by Django 2.0.5 on 2018-06-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20180522_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xiangmu',
            name='xmFaGaiPiWen',
        ),
        migrations.RemoveField(
            model_name='xiangmu',
            name='xmJianSheDanWei',
        ),
        migrations.DeleteModel(
            name='FaGaiPiWen',
        ),
        migrations.DeleteModel(
            name='JianSheDanWei',
        ),
        migrations.DeleteModel(
            name='XiangMu',
        ),
    ]
