# Generated by Django 2.0.5 on 2018-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MengTouBiaoShi',
            fields=[
                ('ljxh', models.CharField(max_length=50)),
                ('bh', models.AutoField(primary_key=True, serialize=False)),
                ('sqdw', models.CharField(max_length=50)),
                ('sgdw', models.CharField(max_length=50)),
                ('sgdd', models.CharField(max_length=50)),
                ('sgqsrq', models.DateField()),
                ('sgzzrq', models.DateField()),
                ('syqsrq', models.DateField()),
                ('syzzrq', models.DateField()),
                ('gcnr', models.CharField(max_length=50)),
                ('gcdd', models.CharField(max_length=50)),
                ('gcmc', models.CharField(max_length=50)),
                ('jg', models.CharField(max_length=50)),
                ('cs', models.CharField(max_length=50)),
                ('ds', models.CharField(max_length=50)),
                ('jzmj', models.CharField(max_length=50)),
                ('cd', models.CharField(max_length=50)),
                ('kd', models.CharField(max_length=50)),
                ('dong', models.CharField(max_length=50)),
                ('nan', models.CharField(max_length=50)),
                ('xi', models.CharField(max_length=50)),
                ('bei', models.CharField(max_length=50)),
                ('bzrq', models.CharField(max_length=50)),
            ],
        ),
    ]
