# Generated by Django 2.0.3 on 2018-11-02 04:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ljxh', models.CharField(blank=True, max_length=50, null=True, verbose_name='临时建设许可证号')),
                ('sqdw', models.CharField(blank=True, max_length=50, null=True, verbose_name='申请单位')),
                ('sgdw', models.CharField(default='自建', max_length=50, verbose_name='施工单位 ')),
                ('sgdd', models.CharField(blank=True, max_length=50, null=True, verbose_name='施工地点 ')),
                ('sgqsrq', models.DateField(verbose_name='施工起始日期')),
                ('sgzzrq', models.DateField(verbose_name='施工终止日期')),
                ('syqsrq', models.DateField(verbose_name='证件有效期起始日期')),
                ('syzzrq', models.DateField(verbose_name='证件有效期终止日期')),
                ('gcnr', models.CharField(default='门头装修', max_length=50, verbose_name='工程内容')),
                ('gcmc', models.CharField(default='门头装修', max_length=50, verbose_name='工程名称')),
                ('mj', models.FloatField(verbose_name='面积')),
                ('cd', models.FloatField(verbose_name='宽度')),
                ('kd', models.FloatField(verbose_name='长度')),
                ('dong', models.CharField(blank=True, max_length=50, null=True, verbose_name='东  ')),
                ('nan', models.CharField(blank=True, max_length=50, null=True, verbose_name='南  ')),
                ('xi', models.CharField(blank=True, max_length=50, null=True, verbose_name='西  ')),
                ('bei', models.CharField(blank=True, max_length=50, null=True, verbose_name='北  ')),
                ('isPrint', models.BooleanField(default=False, verbose_name='打印')),
                ('sbrq', models.DateTimeField(default=django.utils.timezone.now, verbose_name='申报日期')),
                ('bzrq', models.DateTimeField(verbose_name='办证日期')),
            ],
            options={
                'ordering': ('-sbrq',),
            },
        ),
    ]
